### PR TITLE
Update

### PR DESCRIPTION
**Pull request by oliver-zehentleitner**
Hello!
I needed perfdata metrics in the output and made some modifications, if you like them feel free to merge!
This plugin is compatible with NAGIOS and ICINGA, so i updated the readme file and info text.
I would like to suggest you, to create a release and to upload the check_command to to icinga and nagios exchange site as mentioned in the TODO file ...
Best regards,
Oliver

### CODE REVIEW

**Comment by mpibpc-mroose** [comment]
Hi Oliver, thanks for your contribution. If you fix the failing unittest I will be glad to merge ;-)

**Comment by oliver-zehentleitner** [comment]
i adopted the tests and made some necessary changes in check_pcmeasure.py

**Comment by mpibpc-mroose** [comment]
Thanks a lot for your contribution!

**Comment by oliver-zehentleitner** [comment]
Your welcome!
I highly recommend to upload the release to nagios and icinga exchange, you can post the url of this github repo in the description and all together can help to lead more people to this project!
I would do it, but i think it should be in the hands of the maintainer ... 
Best regards!

**Comment by oliver-zehentleitner** [comment]
Ah, this wasnt overtaken with the merge:
Screenshot_20190613_134439
"Nagios/Icinga2 Plugin for https://messpc.de/ and https://pcmeasure.com Ethernet Boxes written in Python 3"

**Pull request merged**
